export interface Company {
  id: number;
  name: string;
  industry: string;
  location: string;
  employees: number;
  founded: number;
  revenue: string;
  ceo: string;
  status: "Active" | "Inactive" | "Pending";
}

export const companiesData: Company[] = [
  {
    id: 1,
    name: "TechMahindra Solutions",
    industry: "Technology",
    location: "Pune, Maharashtra",
    employees: 3500,
    founded: 2008,
    revenue: "₹450 Cr",
    ceo: "Rajesh Kumar",
    status: "Active",
  },
  {
    id: 2,
    name: "IndusBank Financial",
    industry: "Finance",
    location: "Mumbai, Maharashtra",
    employees: 5200,
    founded: 1995,
    revenue: "₹1250 Cr",
    ceo: "Priya Sharma",
    status: "Active",
  },
  {
    id: 3,
    name: "HealthCare Plus India",
    industry: "Healthcare",
    location: "Bangalore, Karnataka",
    employees: 1850,
    founded: 2012,
    revenue: "₹320 Cr",
    ceo: "Dr. Amit Patel",
    status: "Active",
  },
  {
    id: 4,
    name: "GreenPower Energy",
    industry: "Energy",
    location: "Ahmedabad, Gujarat",
    employees: 920,
    founded: 2015,
    revenue: "₹280 Cr",
    ceo: "Vikram Desai",
    status: "Active",
  },
  {
    id: 5,
    name: "Retail Junction Ltd",
    industry: "Retail",
    location: "Delhi, NCR",
    employees: 8400,
    founded: 2003,
    revenue: "₹890 Cr",
    ceo: "Meera Gupta",
    status: "Active",
  },
  {
    id: 6,
    name: "CloudTech Systems",
    industry: "Technology",
    location: "Hyderabad, Telangana",
    employees: 2100,
    founded: 2010,
    revenue: "₹380 Cr",
    ceo: "Arjun Reddy",
    status: "Active",
  },
  {
    id: 7,
    name: "Bharat Auto Motors",
    industry: "Automotive",
    location: "Chennai, Tamil Nadu",
    employees: 4200,
    founded: 2005,
    revenue: "₹650 Cr",
    ceo: "Suresh Krishnan",
    status: "Inactive",
  },
  {
    id: 8,
    name: "FastMove Logistics",
    industry: "Logistics",
    location: "Kolkata, West Bengal",
    employees: 1650,
    founded: 2014,
    revenue: "₹420 Cr",
    ceo: "Ananya Banerjee",
    status: "Active",
  },
  {
    id: 9,
    name: "EduNation Platform",
    industry: "Education",
    location: "Jaipur, Rajasthan",
    employees: 780,
    founded: 2018,
    revenue: "₹185 Cr",
    ceo: "Rohan Mehta",
    status: "Pending",
  },
  {
    id: 10,
    name: "Bollywood Media House",
    industry: "Media",
    location: "Mumbai, Maharashtra",
    employees: 1200,
    founded: 2011,
    revenue: "₹295 Cr",
    ceo: "Karan Kapoor",
    status: "Active",
  },
  {
    id: 11,
    name: "SecureBank India",
    industry: "Finance",
    location: "Bangalore, Karnataka",
    employees: 6800,
    founded: 1992,
    revenue: "₹1850 Cr",
    ceo: "Deepak Verma",
    status: "Active",
  },
  {
    id: 12,
    name: "BioMed Innovations",
    industry: "Healthcare",
    location: "Pune, Maharashtra",
    employees: 520,
    founded: 2019,
    revenue: "₹125 Cr",
    ceo: "Dr. Sneha Iyer",
    status: "Pending",
  },
  {
    id: 13,
    name: "Construction Kings",
    industry: "Construction",
    location: "Gurgaon, Haryana",
    employees: 2400,
    founded: 2009,
    revenue: "₹540 Cr",
    ceo: "Manish Agarwal",
    status: "Active",
  },
  {
    id: 14,
    name: "DataWise Analytics",
    industry: "Technology",
    location: "Noida, Uttar Pradesh",
    employees: 980,
    founded: 2016,
    revenue: "₹245 Cr",
    ceo: "Pooja Singh",
    status: "Active",
  },
  {
    id: 15,
    name: "FashionBazaar Retail",
    industry: "Retail",
    location: "Surat, Gujarat",
    employees: 3200,
    founded: 2007,
    revenue: "₹580 Cr",
    ceo: "Nishant Shah",
    status: "Active",
  },
  {
    id: 16,
    name: "Aerospace India Ltd",
    industry: "Aerospace",
    location: "Bangalore, Karnataka",
    employees: 3800,
    founded: 2004,
    revenue: "₹920 Cr",
    ceo: "Captain Ravi Nair",
    status: "Active",
  },
  {
    id: 17,
    name: "CyberShield Security",
    industry: "Technology",
    location: "Chennai, Tamil Nadu",
    employees: 650,
    founded: 2020,
    revenue: "₹145 Cr",
    ceo: "Aditya Malhotra",
    status: "Pending",
  },
  {
    id: 18,
    name: "AgriGrow Foods",
    industry: "Agriculture",
    location: "Chandigarh, Punjab",
    employees: 1100,
    founded: 2013,
    revenue: "₹365 Cr",
    ceo: "Harpreet Kaur",
    status: "Active",
  },
];